### ISSUE TITLE
fix bouncing html page

### ISSUE THREAD

**Issue by shaynefw** [shaynefw/TravelersChoice#91]

**Comment by shaynefw** [comment]
```css
body {
  height: 100%;
  overscroll-behavior-y: none;
}
```
